name: CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test & Quality Checks

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'finance-tracker/package-lock.json'

    - name: Install dependencies
      run: |
        cd finance-tracker
        npm ci

    - name: Run ESLint
      run: |
        cd finance-tracker
        npm run lint

    - name: Run TypeScript check
      run: |
        cd finance-tracker
        npx tsc --noEmit

    - name: Run tests
      run: |
        cd finance-tracker
        npm run test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./finance-tracker/coverage
        fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    name: Build Application
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'finance-tracker/package-lock.json'

    - name: Install dependencies
      run: |
        cd finance-tracker
        npm ci

    - name: Build application
      run: |
        cd finance-tracker
        npm run build
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: next-build
        path: finance-tracker/.next/

  deploy-preview:
    runs-on: ubuntu-latest
    name: Deploy Preview (Vercel)
    needs: [test, build]
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Vercel (Preview)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: finance-tracker
        scope: ${{ secrets.VERCEL_ORG_ID }}

  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy Production (Vercel)
    needs: [test, build]
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Vercel (Production)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        working-directory: finance-tracker
        scope: ${{ secrets.VERCEL_ORG_ID }}

  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'finance-tracker/package-lock.json'

    - name: Install dependencies
      run: |
        cd finance-tracker
        npm ci

    - name: Run npm audit
      run: |
        cd finance-tracker
        npm audit --audit-level moderate
